services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./var/www/html/app:/var/www/html:z  # shared volume with :z
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./var/www/html/app:/var/www/html:z  # same shared volume
      - ./ssl:/etc/nginx/ssl:ro,z           # mount your certs read-only
      - ./logs/nginx:/var/log/nginx:z
    depends_on:
      - php
    restart: unless-stopped
